// src/lib/dummyData.ts
// ダミーデータ（Supabase接続前のテスト用）

import { Shop, OnlineMerchant } from '@/types';

export const dummyShops: Shop[] = [
  {
    id: '1',
    name: 'Crypto Cafe Tokyo',
    address: '東京都渋谷区神宮前1-2-3',
    lat: 35.6695,
    lng: 139.7025,
    jpyc_networks: ['Ethereum', 'Polygon'],
    payment_methods: ['QRコード決済', 'ウォレット送金'],
    url: 'https://example.com/crypto-cafe',
    tags: ['カフェ', 'コワーキング'],
    status: 'approved',
    created_by: null,
    upvotes: 15,
    downvotes: 2,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'Web3 Burger',
    address: '東京都新宿区新宿3-4-5',
    lat: 35.6896,
    lng: 139.7006,
    jpyc_networks: ['Polygon', 'Avalanche'],
    payment_methods: ['QRコード決済'],
    url: 'https://example.com/web3-burger',
    tags: ['レストラン', 'ファストフード'],
    status: 'approved',
    created_by: null,
    upvotes: 22,
    downvotes: 1,
    created_at: '2024-02-01T00:00:00Z',
    updated_at: '2024-02-01T00:00:00Z',
  },
  {
    id: '3',
    name: 'NFT Art Gallery',
    address: '東京都港区六本木6-7-8',
    lat: 35.6627,
    lng: 139.7295,
    jpyc_networks: ['Ethereum'],
    payment_methods: ['ウォレット送金'],
    url: 'https://example.com/nft-gallery',
    tags: ['アート', 'ギャラリー'],
    status: 'approved',
    created_by: null,
    upvotes: 8,
    downvotes: 0,
    created_at: '2024-03-01T00:00:00Z',
    updated_at: '2024-03-01T00:00:00Z',
  },
  {
    id: '4',
    name: 'Blockchain Books',
    address: '東京都千代田区神田神保町1-2-3',
    lat: 35.6959,
    lng: 139.7576,
    jpyc_networks: ['Polygon'],
    payment_methods: ['QRコード決済', 'ウォレット送金'],
    url: 'https://example.com/blockchain-books',
    tags: ['書店', '技術書'],
    status: 'approved',
    created_by: null,
    upvotes: 12,
    downvotes: 3,
    created_at: '2024-04-01T00:00:00Z',
    updated_at: '2024-04-01T00:00:00Z',
  },
];

export const dummyOnlineMerchants: OnlineMerchant[] = [
  {
    id: '1',
    name: 'CryptoMall',
    description: '仮想通貨で購入できるオンラインモール。日用品から電子機器まで幅広く取り扱い。',
    service_type: 'ECサイト',
    url: 'https://cryptomall.example.com',
    platforms: ['Web', 'iOS', 'Android'],
    jpyc_use_case: '商品購入',
    country: '日本',
    tags: ['ショッピング', 'EC', '日用品'],
    status: 'approved',
    created_by: null,
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-01-15T00:00:00Z',
  },
  {
    id: '2',
    name: 'GameFi Arena',
    description: 'Play-to-Earnゲームプラットフォーム。JPYCでゲーム内アイテムを購入可能。',
    service_type: 'ゲーム',
    url: 'https://gamefi-arena.example.com',
    platforms: ['Web', 'PC'],
    jpyc_use_case: 'ゲーム内課金',
    country: '日本',
    tags: ['ゲーム', 'GameFi', 'NFT'],
    status: 'approved',
    created_by: null,
    created_at: '2024-02-20T00:00:00Z',
    updated_at: '2024-02-20T00:00:00Z',
  },
  {
    id: '3',
    name: 'NFT Marketplace Plus',
    description: 'NFTの売買プラットフォーム。JPYCで直接NFTを購入できます。',
    service_type: 'NFTマーケット',
    url: 'https://nft-marketplace.example.com',
    platforms: ['Web'],
    jpyc_use_case: 'NFT購入',
    country: '日本',
    tags: ['NFT', 'アート', 'コレクタブル'],
    status: 'approved',
    created_by: null,
    created_at: '2024-03-10T00:00:00Z',
    updated_at: '2024-03-10T00:00:00Z',
  },
  {
    id: '4',
    name: 'DeFi Savings',
    description: 'JPYCを預けて利回りを得られるDeFiプラットフォーム。',
    service_type: 'DeFi',
    url: 'https://defi-savings.example.com',
    platforms: ['Web'],
    jpyc_use_case: 'ステーキング・預金',
    country: '日本',
    tags: ['DeFi', '資産運用', 'イールド'],
    status: 'approved',
    created_by: null,
    created_at: '2024-04-05T00:00:00Z',
    updated_at: '2024-04-05T00:00:00Z',
  },
  {
    id: '5',
    name: 'Crypto Gift Cards',
    description: '各種ギフトカードをJPYCで購入可能。Amazon、iTunes、Google Playなど対応。',
    service_type: 'ギフトカード',
    url: 'https://crypto-giftcards.example.com',
    platforms: ['Web', 'iOS', 'Android'],
    jpyc_use_case: 'ギフトカード購入',
    country: '日本',
    tags: ['ギフトカード', 'ショッピング'],
    status: 'approved',
    created_by: null,
    created_at: '2024-05-01T00:00:00Z',
    updated_at: '2024-05-01T00:00:00Z',
  },
  {
    id: '6',
    name: 'Web3 Learning Hub',
    description: 'ブロックチェーン・Web3の学習プラットフォーム。JPYCでコースを購入。',
    service_type: '教育',
    url: 'https://web3-learning.example.com',
    platforms: ['Web'],
    jpyc_use_case: 'コース購入',
    country: '日本',
    tags: ['教育', '学習', 'ブロックチェーン'],
    status: 'approved',
    created_by: null,
    created_at: '2024-06-15T00:00:00Z',
    updated_at: '2024-06-15T00:00:00Z',
  },
];
